---
- name: Update apt cache
  apt:
    update_cache: yes
  tags: ['common', 'init']

- name: Install common packages
  apt:
    name:
      - curl
      - wget
      - gnupg
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - build-essential
      - nginx
      - ufw
    state: present
  tags: ['common', 'packages']

- name: Configure UFW
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - '22'    # SSH
    - '80'    # HTTP
    - '443'   # HTTPS
  tags: ['common', 'security']

- name: Enable UFW
  ufw:
    state: enabled
  tags: ['common', 'security']

- name: Deploy Node.js Application
  hosts: app_servers
  become: yes
  vars_files:
    - vars/main.yml
  
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

  roles:
    - nodejs
    - pm2
    - nginx
    - app_deploy

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted

    - name: reload nginx
      service:
        name: nginx
        state: reloaded