---
# Nginx-specific configuration variables
nginx_config:
  # Worker settings
  worker_processes: auto
  worker_connections: 1024
  
  # Connection handling
  keepalive_timeout: 65
  keepalive_requests: 100
  client_max_body_size: "10M"
  client_body_timeout: 60s
  client_header_timeout: 60s
  send_timeout: 60s
  
  # Proxy settings
  proxy_connect_timeout: 60s
  proxy_send_timeout: 60s
  proxy_read_timeout: 60s
  proxy_buffer_size: "4k"
  proxy_buffers: "4 32k"
  proxy_busy_buffers_size: "64k"
  
  # SSL settings (if using HTTPS)
  ssl_protocols: "TLSv1.2 TLSv1.3"
  ssl_ciphers: "HIGH:!aNULL:!MD5"
  ssl_session_timeout: "1d"
  ssl_session_cache: "shared:SSL:50m"
  
  # Gzip settings
  gzip: true
  gzip_min_length: 1000
  gzip_comp_level: 6
  gzip_types:
    - text/plain
    - text/css
    - application/json
    - application/javascript
    - text/xml
    - application/xml
    - application/xml+rss
    - text/javascript
  
  # Rate limiting
  rate_limit:
    enable: true
    zone_size: "10m"
    rate: "30r/s"
    burst: 10
  
  # Logging
  access_log: "/var/log/nginx/{{ shared_vars.app_name }}_access.log"
  error_log: "/var/log/nginx/{{ shared_vars.app_name }}_error.log"
  
  # Cache settings
  static_file_cache:
    enable: true
    max_age: "7d"
    types:
      - jpg
      - jpeg
      - png
      - gif
      - ico
      - css
      - js

  # Security headers
  security_headers:
    X-Frame-Options: "SAMEORIGIN"
    X-XSS-Protection: "1; mode=block"
    X-Content-Type-Options: "nosniff"
    Strict-Transport-Security: "max-age=31536000; includeSubDomains"
    Content-Security-Policy: "default-src 'self'"