---
- name: Install Redis
  apt:
    name: redis-server
    state: present
    update_cache: yes

- name: Copy Redis configuration
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
    owner: redis
    group: redis
    mode: '0644'
  notify: restart redis

- name: Copy Redis service file
  template:
    src: redis.service.j2
    dest: /etc/systemd/system/redis.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - reload systemd
    - restart redis

- name: Ensure Redis is started and enabled
  systemd:
    name: redis
    state: started
    enabled: yes
