---
- name: Install MySQL
  apt:
    name: 
      - mysql-server
      - python3-mysqldb
    state: present
    update_cache: yes

- name: Copy MySQL configuration
  template:
    src: my.cnf.j2
    dest: /etc/mysql/my.cnf
    owner: root
    group: root
    mode: '0644'
  notify: restart mysql

- name: Copy MySQL service file
  template:
    src: mysql.service.j2
    dest: /etc/systemd/system/mysql.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - reload systemd
    - restart mysql

- name: Ensure MySQL is started and enabled
  systemd:
    name: mysql
    state: started
    enabled: yes