name: Dev Pipeline - For All Branches (except main)

on:
  push:
    branches:
      - "*"
    # Excluding the main branch
      - '!main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Load Environment Variables for Dev
      run: |
        cp .env.dev .env # Copy .env.dev into .env
        echo "DB_CONNECTION_STRING=${{ secrets.DB_CONNECTION_STRING_DEV }}" >> $GITHUB_ENV
        echo "FIREBASE_CLI_TOKEN=${{ secrets.FIREBASE_CLI_TOKEN }}" >> $GITHUB_ENV

    - name: Install Dependencies (Frontend and Backend)
      run: |
        cd user-facing-backend/Express-Typescript
        npm install
        cd ../user-facing-frontend/React-Typescript
        npm install

    - name: Lint Code
      run: |
        cd user-facing-backend/Express-Typescipt
        npm run lint
        cd ../user-facing-frontend/React-Typescript
        npm run lint

    - name: Run Tests
      run: |
        cd user-facing-backend/Express-Typescript
        npm test
        cd ../user-facing-frontend/React-Typescript
        npm test

    - name: Build Frontend
      run: |
        cd user-facing-frontend/React-Typescript
        npm run build
        cp -r build/* ../user-facing-backend/Express-Typescript/public/build/

    - name: Deploy to Firebase Dev
      run: |
        cd user-facing-backend/Express-Typescript
        firebase deploy --only hosting --token $FIREBASE_CLI_TOKEN

    - name: Update PR with Staging URL
      run: |
        echo "Staging URL: https://dev-firebase-url.com" # Replace with actual dev URL